---
openapi: 3.0.3
info:
  version: 0.1.0
  title: ERP REST API
  description: REST API для ERP в формате OpenAPI v3.
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  contact:
    name: Nazarov Andrey